parameters:
  - name: imageRepository
    type: string
    default: 'voteapp'
  - name: tag
    type: string
    default: 'latest'

stages:
- stage: Deploy
  displayName: 'Deploy to Kubernetes'
  dependsOn: Build
  jobs:
  - deployment:
    condition: ne(variables['Build.Reason'], 'PullRequest')
    environment: 'aks-uks-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(manifestName).yaml
          
          - task: KubernetesManifest@0
            displayName: Deploy
            inputs:
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: default
              manifests: |
                $(Pipeline.Workspace)/$(manifestName).yaml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)