parameters:
  - name: imageRepository
    type: string
    default: 'voteapp'
  - name: dockerRegistryServiceConnection
    type: string
    default: 'myDockerRegistryServiceConnection'
  - name: tag
    type: string
    default: 'latest'
stages:
- stage:
  displayName: 'Deploy to Kubernetes'
  dependsOn: Build
  jobs:
  - deployment: DeployToAKS
    condition: ne(variables['Build.Reason'], 'PullRequest')
    environment: 'aks-uks-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(manifestName).yaml
          - task: KubernetesManifest@0
            displayName: Deploy
            inputs:
              # kubernetesServiceConnection: someK8sSC1
              namespace: default
              manifests: |
                $(Pipeline.Workspace)/$(manifestName).yaml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)